version: '2'
services:
  db:
    build: ./db
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pablo
      - MYSQL_USER=pablo
      - MYSQL_PASSWORD=root
  api:
    build: ./api
    ports:
      - "8085:8085"
      - "37871:37871"
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - ./api:/api
  client:
    build: ./client
    ports:
      - "4200:4200"
      - "80:3000"
    volumes:
      - ./client:/client
